### ISSUE TITLE
Adding `/var/labels` folder to default configuration

### ISSUE THREAD

**Issue by Moongazer** [sourcebroker/deployer-extended-typo3#13]
The `/var/labels` folder is used to store the label files downloaded by [Manage Language Packs](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Internationalization/ManagingTranslations.html).

Currently after each deployment, all language packs have to be manually downloaded again, because this folder is not set in `shared_dirs`. One could add this to their custom Deployer config, but IMO it make sense to add this to the default `shared_dirs` config similar to `/var/log` and `/var/transient`:
```
set('shared_dirs', function () {
    return [
        // ...
        !empty(get('web_path')) ? 'var/labels' : 'typo3temp/var/labels',
    ];
});
```
Alternatively, the deployment script should run `/path/to/typo3/bin/typo3 language:update` after changing the deployment-dir, to trigger the full download of all the files, if the folder should stay at its current place (`/current/var/labels`).

**Comment by kszymukowicz** [comment]
This is arguable if:
1. `/var/labels` should be in shared or not
2. if in shared should it be updated on each deploy

Also in core documentation the  `/var/labels` is in git:
https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/Installation/DeployTYPO3.html#deployment-automation

TYPO3 Core Distribution also have `/var/labels` in git:
https://github.com/TYPO3/TYPO3.CMS.BaseDistribution/blob/master/.gitignore
My opinion is that it should be in git and updated only when needed. So when you updated extension and you miss some label.
