### ISSUE TITLE
deploy task and "web_path"

### ISSUE THREAD

**Issue by tazeverywhere** [sourcebroker/deployer-extended-typo3#2]
Hi @kszymukowicz ,

First thank you for this great deployer-extended for typo3 ! nice addons and media/db pull/push are very usefull!

I succefully deployed my first test with deployer-extended, but is it correct that to end with correct deployment, I had to set `web_path`, and set shared dirs, files and media accordingly ?

in my deploy.php I have now:

```php
set('web_path', 'web');

set(
    'shared_dirs',
    [
        '{{web_path}}/fileadmin',
        '{{web_path}}/uploads',
        '{{web_path}}/typo3temp',
    ]
);

set('shared_files', [
    '.env',
    '{{web_path}}/.htaccess'
]);

set(
    'media',
    [
        'filter' => [
            '+ */',
            '+ {{web_path}}/fileadmin/',
            '+ {{web_path}}/fileadmin/**',
            '+ {{web_path}}/uploads/',
            '+ {{web_path}}/uploads/**',
            '- *'
        ]
    ]
);
```
Like this it work, but I have to use `deploy-fast` task, because de "buffer-start" part doesn't work with "web_path" sub-folder in my test. Any idea ?

Actually on typo3 8.7

Thanks for your feedback,
Sylvain

**Comment by tazeverywhere** [comment]
Ha, of course, setting `buffer_config` with web_path prefix works ;)

```php
// Look on https://github.com/sourcebroker/deployer-extended#buffer-start for docs
set(
    'buffer_config',
    [
        'index.php' => [
            'entrypoint_filename' => '{{web_path}}/index.php',
        ]
    ]
);
```

Anyway, is this the way to (you) go ?
Thanks for feedback and help.

**Comment by kszymukowicz** [comment]
hi @tazeverywhere 

I currently use the old way of file organisation in TYPO3 (all in root without /web) and I block access to sensitive files with .htaccess.

The current version of "deployer-extended-typo3" supports by default the old way of file organisation however it can be configured to use "web_path" **exactly as you did**.

Anyway your deploy.php file is bigger now because you needed to do additional configuration for "web_path". This should be supported by default by "deployer-extended-typo3" and I will do implement it in next version.

**Comment by tazeverywhere** [comment]
Hi @kszymukowicz ,

Sorry for late reply, thanks for your feedback, I will keep an eye on future version ;)

Btw, thanks again so much for those packages, very usefull for me, a real pleasure to work with typo3 & deployer (extended).

**Comment by kszymukowicz** [comment]
BTW: 
In most new version 12.1.0 you can now set only:
`set('web_path', 'public/');` 
and all will work automatically. No more configuration needed.

**Comment by tazeverywhere** [comment]
Hey @kszymukowicz ,
thank you for feedback, very cool ! I will test that asap.
thanks for those great Deployer components, I use it now with all my framework: Typo3, Codeigniter, Wordpress Bedrock/Sage.. easy to setup and very usefull!
Best.
