### ISSUE TITLE
[TASK] Allow setting path to TYPO3-sources

### ISSUE THREAD

**Issue by mavolkmer** [sourcebroker/deployer-extended-typo3#20]
When using `helhum/typo3-secure-web` TYPO3-sources are placed into `/private` where `deloyer-extended-typo3` has folder `public` hard-coded when folder `typo3` is not found in project-root.

Please have a look at #19 for a possible way to configure this path without changing current behaviour.

**Comment by kszymukowicz** [comment]
Tnx for taking care or this issue! Plz check for solution in 18.0.0.
