### ISSUE TITLE
Not compatible with typo3/cms-composer-installers v4

### ISSUE THREAD

**Issue by Starraider** [sourcebroker/deployer-extended-typo3#22]
With the new typo3/cms-composer-installers version 4.x all the TYPO3 extensions are moved to the vendor folder.
More information about this can be found here:

- https://b13.com/core-insights/typo3-and-composer-weve-come-a-long-way
- https://brot.krue.ml/migration-typo3-composer-cms-installers-version-4/

Currently deployer-extended-typo3 is not working any more with typo3/cms-composer-installers version 4.x, because the old path to the (system) extensions are used.
For example in the src/Loader.php line 38 and 39:
***
$changelogFilesRoot = glob($rootDir . '/typo3/sysext/core/Documentation/Changelog-*.rst');
$changelogFilesRootSubDirs = glob($rootDir . '/*/typo3/sysext/core/Documentation/Changelog-*.rst');
***
These files are now in '/vendor/typo3/cms-core/Documentation/

**Comment by maikschneider** [comment]
@kszymukowicz Successfully tested #24

**Comment by mikestreety** [comment]
Have just tested my end and works perfectly 👍

**Comment by kszymukowicz** [comment]
hi guys,
thank you for providing patches and conducting tests.
changes integrated into 18.1.0.
