### ISSUE TITLE
  Package deployer/dist is abandoned

### ISSUE THREAD

**Issue by develth** [sourcebroker/deployer-extended-typo3#25]
Hi,

just got an message through deployment:

` Package deployer/dist is abandoned, you should avoid using it. Use deployer/deployer instead.`

Is it safe to replace?
Thanks!

**Comment by kszymukowicz** [comment]
hi,

the latest stable version of deployer is 6.8.0 and its used by `deployer-extended-typo3`. The author of deployer is doing 7.x from two years already and its still beta/RC.

As far as I understand the info `Package deployer/dist is abandoned` is more for version 7.x. For this version author of deployer will no longer support `deployer/dist`. Unfortunately you can not abandon Packagist project only for some tags and this is why we see this message.

When deployer will have official stable version 7.x I will switch from `deployer/dist` to `deployer/deployer`.

**Comment by maikschneider** [comment]
Deployer v7 has been released! :)

@kszymukowicz Are there already plans for the upgrade of the deployer-extended-typo3 package? There are quite a few deployer-extended-* packages to migrate - let me know if I can help you.

**Comment by kszymukowicz** [comment]
@maikschneider 

Sure there are plans :)
Unfortunately I have too many deadlines in next weeks.

**Comment by kszymukowicz** [comment]
@develth @maikschneider 
it took some time but you can try now v20.0.0 with deployer 7 support!

**Comment by maikschneider** [comment]
@kszymukowicz I've tested the new version last week and encountered no problems at all - really good work, thank you! Where is your sponsor button, would love to show some appreciation.
