### ISSUE TITLE
Executing task db:backup doesn't find dep phar file

### ISSUE THREAD

**Issue by Starraider** [sourcebroker/deployer-extended-typo3#3]
Hi!
Thanks for your great work!
Unfortunately I can't bring the first deployment to the beta server to work.
In the "Executing task db:backup" section I always get the following error message:
```
****
In set.php line 94:                                                                                                       
  [Deployer\Exception\GracefulShutdownException]                                                       
  There must be ~/html/myProject/beta/release/vendor/bin/dep phar file, but it could not be found.
****
```
But if I check for the dep phar file, it's there (or at least a symlink, because I use deployer/dist as you recommend).
I can't figure out, why it's not working.

Here you can find my deployer.php file:
[deployer.php](https://github.com/Starraider/devTypo3ddev/blob/master/deploy.php)

Please can you help?

**Comment by kszymukowicz** [comment]
No idea. Can you give whole log here?

**Comment by Starraider** [comment]
Here is the log:
***
➤ Executing task deploy:unlock
[beta] > rm -f /home/www/p203341/html/devTypo3ddev/beta/.dep/deploy.lock
• done on [beta]
✔ Ok [1s 111ms]

In Client.php line 103:
                                                                                                                  
  [Deployer\Exception\RuntimeException (127)]                                                                     
  The command " -r "clearstatcache(true);if(function_exists('opcache_reset')) opcache_reset();if(function_exists  
  ('eaccelerator_clear')) eaccelerator_clear();"" failed.                                                         
                                                                                                                  
  Exit Code: 127 (Command not found)                                                                              
                                                                                                                  
  Host Name: beta                                                                                                 
                                                                                                                  
  ================                                                                                                
  bash: line 1: -r: command not found                                                                             
                                                                                                                  

Exception trace:
  at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/src/Ssh/Client.php:103
 Deployer\Ssh\Client->run() at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/src/functions.php:304
 Deployer\run() at /Users/sven/Documents/Projekte/devTypo3ddev/vendor/sourcebroker/deployer-extended/deployer/cache/task/cache_clear_php_cli.php:7
 SourceBroker\DeployerLoader\Utility\FileUtility->Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/src/Task/Task.php:105
 Deployer\Task\Task->run() at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/src/Executor/SeriesExecutor.php:60
 Deployer\Executor\SeriesExecutor->run() at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/src/Console/TaskCommand.php:144
 Deployer\Console\TaskCommand->execute() at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/vendor/symfony/console/Application.php:924
 Symfony\Component\Console\Application->doRunCommand() at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/src/Console/Application.php:133
 Deployer\Console\Application->doRunCommand() at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/vendor/symfony/console/Application.php:265
 Symfony\Component\Console\Application->doRun() at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/vendor/symfony/console/Application.php:141
 Symfony\Component\Console\Application->run() at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/src/Deployer.php:326
 Deployer\Deployer::run() at phar:///Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep/bin/dep:134
 require() at /Users/sven/Documents/Projekte/devTypo3ddev/vendor/deployer/dist/dep:4
***

**Comment by kszymukowicz** [comment]
Its not a full log.

**Comment by kszymukowicz** [comment]
try `php vendor/bin/dep deploy -vvv beta > log.txt`

**Comment by Starraider** [comment]
I found out, what the problem is:

If I use:
`set('bin/php', '/usr/local/bin/php');`
at the "deploy:vendors" task something like this will be generated:
`... /usr/local/bin/php /usr/local/bin/composer install ...`
which doesn't work.

Because if I do:
`/usr/local/bin/php_cli /usr/local/bin/composer -V`
this is the output:
`#composer per cli
export COMPOSER_HOME=/files/swm2/composer/.composer
php_cli /files/swm2/composer/composer.phar $@`

So instead of using: 
`set('bin/php', '/usr/local/bin/php');` 
I used:
`set('bin/php', '');` 
which makes composer work just fine.
But then in the "cache-clear-php-cli" something like this will be generated:
`" -r "clearstatcache(true);if(function_exists('opcache_reset'))...`
which means the `/usr/local/bin/php` is missing in the front of the command.

Any ideas, how to fix this?
Or wouldn't it be better to use composer without php in front? I mean `which composer` should be enough to get a running composer, right?

**Comment by kszymukowicz** [comment]
The `deploy:vendors` is task from deployer core. I do not change it at all in deployer-extended-typo3.

Additionally I use `set('bin/php', ..` on lot of hostings and I never had a problem like yours. So I suppose your problem is some hoster specific.

**Comment by Starraider** [comment]
Yes, I agree with you. This is a problem in the doployer core.

I googled a bit more and finally I found a solution:
If I use `/files/swm2/composer/composer.phar` it would work with php in front of it.
Luckily you can set `bin/composer` as well.
But strangely if you `set('bin/composer', '/files/swm2/composer/composer.phar')` the `bin/php` is not set in front of it any more, which was the problem in first place. 
So I actually had to do this:
`set('bin/composer', '/usr/local/bin/php /files/swm2/composer/composer.phar')`
Now it works like a charm!

Thanks for your help and for your great work!
