### ISSUE TITLE
task db:export failed

### ISSUE THREAD

**Issue by tzeier** [sourcebroker/deployer-extended-typo3#32]
I always get the error; "Failed to run dep deploy -vvv beta: exit status 255"

Complete Log: [log.txt](https://github.com/sourcebroker/deployer-extended-typo3/files/10428748/log.txt)

There seems to be a problem with the tastk db:export.

**Comment by kszymukowicz** [comment]
First try to make base deploy. 
For that you can disable not required tasks like `db:export`.

In `deploy.php` put 
```
task('db:export')->disable();
```
After first successful deploy try to enable the tasks that failed before.

**Comment by tzeier** [comment]
Thank You. I'll try that.

**Comment by tzeier** [comment]
Tried that. Still the same error.

**Comment by kszymukowicz** [comment]
@tzeier 
please use ` --log deploy.log` and provide log file.

**Comment by tzeier** [comment]
[deploy.log](https://github.com/sourcebroker/deployer-extended-typo3/files/10432151/deploy.log)

**Comment by kszymukowicz** [comment]
And how your deploy.php looks like.

**Comment by kszymukowicz** [comment]
Is deploy.php commited and pushed?

**Comment by kszymukowicz** [comment]
You should actually disable `task('db:backup')->disable();` becase this task is running `db:export` on remote host and `db:backup` is run locally.

Probably next task to disable for now is `task('db:truncate')->disable();` which clear caching tables.

If you do `task('db:backup')->disable();` then you do not have to push deploy.php.

**Comment by tzeier** [comment]
> 
> Is deploy.php commited and pushed?
> 

It is

**Comment by tzeier** [comment]
> @tzeier 
> You should actually disable `task('db:backup')->disable();` becase this task is running `db:export` internally on remote host.
> 
> Probably next task to disable for now is `task('db:truncate')->disable();` which clear caching tables.
> 
> If you do `task('db:backup')->disable();` then you do not have to push deploy.php.
> 

Alright. Thank You. I'll try that...

**Comment by tzeier** [comment]
Still doesn't work...
Failed to run dep deploy beta -vv --log deploy.log: exit status 64
[deploy.log](https://github.com/sourcebroker/deployer-extended-typo3/files/10439026/deploy.log)

**Comment by kszymukowicz** [comment]
In log you see: `mv: illegal option -- T`. This is because of the hostpoint.ch. On other hostings it works ok.
On hostpoint.ch you need to add this to your deploy.php
```
task('buffer:start')->disable(); // mv -T is not working
task('buffer:end')->disable(); // mv -T is not working
task('php:clear_cache_http')->disable(); // no needed because of run('killall -9 php-cgi');

task('deploy:symlink', function () {
    // Atomic symlink does not supported on this hoster. Will use simple two steps switch.
    run("cd {{deploy_path}} && {{bin/symlink}} {{release_path}} current"); // Atomic override symlink.
    run("cd {{deploy_path}} && rm release"); // Remove release link.
    run('killall -9 php-cgi'); // special command to restart php cache on this hoster
});
```

**Comment by tzeier** [comment]
I see. I thought, the problem could be hoster specific.

I added the suggested code to deploy.php. Now I get the following error:

 InvalidArgumentException  in TaskCollection.php on line 21:
  Task `buffer:end` not found.
Failed to run dep deploy -vv beta: exit status 1

**Comment by tzeier** [comment]
ok. I think it's 'buffer:stop' instead of 'buffer:end'
Also it said, that the task 'clear_cache_http' could not be found.

**Comment by kszymukowicz** [comment]
Sry. I copied it from some old `deployer-extended-typo3` version. 
The  `clear_cache_http` should be `cache:clear_php_http`.

**Comment by tzeier** [comment]
> Sry. I copied it from some old `deployer-extended-typo3` version. The `clear_cache_http` should be `cache:clear_php_http`.

OK. That cleared that up. But the debugging goes on...

Now there is a problem with database:updateschema,,, can I disable that too?

[deploy.log](https://github.com/sourcebroker/deployer-extended-typo3/files/10443114/deploy.log)

**Comment by tzeier** [comment]
Alritghy then! With 
`task('typo3cms:database:updateschema')->disable();`
I finally succeded...
Now I have to find a way to set up my database connection. Is there a 'best practise', You would recommend?
AdditionalConfiguration.php with reference to .env Variables?
And also I need to exclude some files from the deploy...

**Comment by tzeier** [comment]
Thank You for Your help so far. 
Now I've got a new porblem. After deplyoing to the server, my static_info_tables extension is missing. The tables are still in database, the extension folder is still in the typo3conf/ext directory, but it isn't listed in my extensions list in BE and it's also not working. What could be the reasons for that behaviour?

**Comment by kszymukowicz** [comment]
This is for sure no not connected to `deployer-extended-typo3`. 
Reason could be that for example you have this package in require-dev section of you composer.json

**Comment by kszymukowicz** [comment]
@einNicklas Plz create a new issue for that and the best delete your post form this thread. Tnx.

**Comment by einNicklas** [comment]
> @einNicklas Plz create a new issue for that and the best delete your post form this thread. Tnx.

#37

**Comment by kszymukowicz** [comment]
No feedback from issue creator so closing.
