### ISSUE TITLE
Support TYPO3 Console 8

### ISSUE THREAD

**Issue by pixelbrackets** [sourcebroker/deployer-extended-typo3#33]
Hey 👋

deployer-extended-typo3 supports a large range of helhum/typo3-console releases. All of them support PHP up to >=7.4.1. The first official suppport release for PHP >= 8.1 is version 8, see https://packagist.org/packages/helhum/typo3-console#v8.0.0

I use PHP 8.1 and can not run deployer-extended-typo3, due to error messages in typo3-console 7.

I thought about adding the version range `|| ^8.0`  to the existing ones, just as in #12,
but then remembered the typo3-console release note that the shipped binary is dropped:

> Since version 8.0.0 the extra binary typo3cms is removed and superseded with the core binary typo3. Commands that were called e.g. typo3cms database:updateschema before, must now be called with typo3 database:updateschema.

The path to the binary is configurable in deployer-extended-typo3:
https://github.com/sourcebroker/deployer-extended-typo3/blob/a5b11887ca63e4c87151303607255de2368feead/deployer/default/set.php#L48-L49

But this the »default« for _all_ TYPO3 versions suported by deployer-extended-typo3 and _all_ versions of typo3-console. So theres a catch22 situation now:
- Add the version 8 requirement and change the default value: Breaking change – Either requires a hint in the installation guide for users of older typo3-console versions, or deployer-extended-typo3 completely drops support for these older versions
- Add the version 8 requirement only and don't change the default value: Requires a blunt message in the installation guide docs, otherwise users of the latest versions of deployer-extended-typo3 and typo3-console get an error message right away, whichs is an unexpected behaviour

Before I send a PR, what are your thoughts on this? Which way would you folks prefer?

**Comment by kszymukowicz** [comment]
hi @pixelbrackets 

plz test the dev-master for TYPO3 12 compatible version.

**Comment by pixelbrackets** [comment]
Ah, [simple and elegant fix for the binary setup](https://github.com/sourcebroker/deployer-extended-typo3/commit/504155ec9f2ea80422029298e3111bed98798f82). Nice, thank you. Will test this asap.
