### ISSUE TITLE
How to pull PDFs and other files? How to modify `exclude-case-insensitive` array

### ISSUE THREAD

**Issue by mikestreety** [sourcebroker/deployer-extended-typo3#36]
Raising this in here, becuase of [this configuration](https://github.com/sourcebroker/deployer-extended-typo3/blob/4e27c75ba1a8793d509cc7a91f228639a2c70472/deployer/default/set.php#L58) but it is kind of an issue with: https://github.com/sourcebroker/deployer-extended-media

In the above repo, a list of files is set to be excluded (https://github.com/sourcebroker/deployer-extended-media/blob/master/deployer/media/config/set.php#L12) - how would I remove `pdf` from this list in my local deploy.php, without having to redefine the array set in this repo?

I've tried everything I can think of but it always results in the `exclude-case-insensitive` including all the file types.

Thanks for a great set of packages :)

**Comment by kszymukowicz** [comment]
@mikestreety 
I must admit overwriting this part was always a pain for me also :)
Therefore I added now a `media_custom` in new `deployer-extended-media` v12.0.0. 
It is integrated in `deployer-extended-typo3` on branch master.
Please test if that works for you.

**Comment by mikestreety** [comment]
Thanks for resolving so quickly, sorry i've not replied I hadn't (and still haven't) had another use-case for this yet!
