### ISSUE TITLE
Web path hard coded to `public`

### ISSUE THREAD

**Issue by mikestreety** [sourcebroker/deployer-extended-typo3#5]
Hi!

Thanks so much for the package & work. 

I hit a bit of a block when I came to deploy though, as `public` is hard-coded in the loader when looking for the TYPO3 version:

https://github.com/sourcebroker/deployer-extended-typo3/blob/master/src/Loader.php#L38

Not quite sure how this would work, but I would expect it to read the `web_path` variable that is set.

Thanks

**Comment by kszymukowicz** [comment]
hi,

Thanks for nice words.

`public` is default when you use TYPO3 composer installation so I do not expect anyone is changing this. At least I do not change it in my TYPO3 installations :)

However if you prepare some nice PR that read it from `web_path` then no problem - I will merge.
